version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=graphdb;Username=postgres;Password=yourpassword
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend
    restart: on-failure

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=graphdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d graphdb || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
    # volumes:
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql